apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappsql 
  namepace: default
  labels:
    name: myappsql-deploy
    tyre: backend 
spec:
  selector:
    matchLabels:
        app: medicalcoder
        tier: backend      
  replicas: 1
  template:
    metadata: 
      name: db
      labels:
        app: medicalcoder
        tier: backend

    spec:
      containers:
        - name: medicalcoderbackend
          image: mrafit20/medicalcodersql:1.0.1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Tasneem1996
            - name: MYSQL_DATABASE
              value: medical
            - name: MYSQL_USER
              value: mrafi
            - name: MYSQL_PASSWORD
              value: Tasneem1996
